# Generated by Django 5.1.4 on 2024-12-10 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='research_project_images/')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('published', 'Published')], default='ongoing', max_length=10)),
            ],
        ),
    ]
