# Generated by Django 5.1.4 on 2024-12-11 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_researchproject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
