# Generated by Django 5.1.4 on 2024-12-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lab_investigator', 'Lab Investigator'), ('ms_thesis_student', 'MS (Thesis) Student'), ('undergraduate_student', 'Undergraduate Student')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
            ],
        ),
    ]
