# Generated by Django 5.1.4 on 2024-12-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='designation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
