# Generated by Django 5.1.4 on 2025-05-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('lab_investigator', 'Lab Investigator'), ('ms_thesis_student', 'MS (Thesis) Student'), ('undergraduate_student', 'Undergraduate Student'), ('alumi', 'Alumni')], max_length=50),
        ),
    ]
