# Generated by Django 5.1.4 on 2025-05-05 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_member_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('lab_investigator', 'Principal Investigator'), ('lab_investigator_co', 'Coinvestigator'), ('ms_thesis_student', 'MS (Thesis) Student'), ('undergraduate_student', 'Undergraduate Student'), ('alumni', 'Alumni')], max_length=50),
        ),
    ]
