# Generated by Django 5.1.4 on 2025-05-05 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_textcontent_alter_member_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bacteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amr_status', models.CharField(max_length=100)),
                ('strain_category', models.CharField(choices=[('clinical', 'Clinical'), ('reference', 'Reference'), ('laboratory', 'Laboratory')], max_length=20)),
                ('source', models.CharField(max_length=255, verbose_name='Source')),
                ('active_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Phage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('information', models.TextField()),
            ],
        ),
    ]
