# Generated by Django 5.1.4 on 2025-05-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_bacteria_phage'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
