# Generated by Django 5.1.4 on 2025-05-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_researchproject_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='category',
            field=models.CharField(choices=[('lab_investigator', 'Principal Investigator'), ('lab_investigator_co', 'Coinvestigator'), ('phd_student', 'PhD Student'), ('ms_thesis_student', 'MS (Thesis) Student'), ('undergraduate_student', 'Undergraduate Student'), ('alumni', 'Alumni')], max_length=50),
        ),
    ]
