# Generated by Django 5.1.4 on 2025-05-30 13:39

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_member_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='content',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
    ]
