# Generated by Django 5.1.4 on 2025-05-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
