# Generated by Django 5.1.4 on 2025-05-30 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_member_teaching_teaching'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teaching',
            name='title',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
