# Generated by Django 5.1.4 on 2025-05-31 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_member_conference_conference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='active_research_project',
        ),
        migrations.RemoveField(
            model_name='member',
            name='education',
        ),
        migrations.RemoveField(
            model_name='member',
            name='external_affiliations',
        ),
        migrations.RemoveField(
            model_name='member',
            name='journal_publications',
        ),
        migrations.RemoveField(
            model_name='member',
            name='previous_research_project',
        ),
        migrations.RemoveField(
            model_name='member',
            name='research_interests',
        ),
        migrations.CreateModel(
            name='ActiveResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='active_research_projects', to='app.member')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='app.member')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_affiliations', to='app.member')),
            ],
        ),
        migrations.CreateModel(
            name='PrevResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_research_projects', to='app.member')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=200, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_interests', to='app.member')),
            ],
        ),
    ]
