# Generated by Django 5.1.4 on 2025-05-31 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_member_active_research_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='graduate_supervision',
        ),
        migrations.AddField(
            model_name='member',
            name='office_address',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='activeresearchproject',
            name='title',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='conference',
            name='title',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='externalaffiliation',
            name='title',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='prevresearchproject',
            name='title',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='url',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='researchinterest',
            name='title',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='title',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='url',
            field=models.URLField(max_length=400),
        ),
        migrations.AlterField(
            model_name='teaching',
            name='title',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='textcontent',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
