# Generated by Django 5.1.4 on 2025-05-31 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_member_graduate_supervision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='biography',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
