# Generated by Django 5.1.4 on 2025-05-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_member_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='biography',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
