# Generated by Django 5.1.4 on 2025-11-15 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_member_biography'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='slider_image',
            field=models.BooleanField(default=False),
        ),
    ]
