# Generated by Django 5.1.4 on 2025-11-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_imagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecontent',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
