# Generated by Django 5.1.4 on 2025-12-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_imagecontent_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='phage',
            name='genetic_information',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='isolation_source',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='life_cycle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='morphology',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='phage',
            name='storage_condition',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='phage',
            name='host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='phage',
            name='information',
            field=models.TextField(blank=True, null=True, verbose_name='Other Information'),
        ),
        migrations.AlterField(
            model_name='phage',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phage Name'),
        ),
    ]
