# Generated by Django 5.1.4 on 2026-03-02 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_phage_genetic_information_phage_isolation_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bacteria',
            name='strain_category',
        ),
        migrations.AddField(
            model_name='bacteria',
            name='molecular_identification',
            field=models.TextField(blank=True, null=True, verbose_name='Molecular Identification (16S)'),
        ),
        migrations.AddField(
            model_name='bacteria',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Notes'),
        ),
        migrations.AddField(
            model_name='bacteria',
            name='storage_temperature',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Storage Temperature'),
        ),
        migrations.AddField(
            model_name='bacteria',
            name='strain_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Strain ID'),
        ),
        migrations.AlterField(
            model_name='bacteria',
            name='active_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Isolation'),
        ),
        migrations.AlterField(
            model_name='bacteria',
            name='amr_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Antibiotic Susceptibility'),
        ),
        migrations.AlterField(
            model_name='bacteria',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Species'),
        ),
    ]
